# Generated by Django 3.0.9 on 2021-03-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=6)),
            ],
        ),
    ]
