# Generated by Django 3.0.9 on 2021-03-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='value',
            new_name='Destination',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='Source',
        ),
    ]
